# Site settings
title: Chipata Tech Hub
email: molinsp@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  CTH Website
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://chipata.tech" # the base hostname & protocol for your site
github_username:  molinsp